import asyncio
import logging
import os
import re
import random
import traceback
import aiohttp
from datetime import datetime, timedelta, timezone
from typing import Optional, Dict, Any, List, Tuple

import discord
from discord.ext import tasks, commands
from discord import app_commands

logging.basicConfig(level = logging.INFO, format = "%(asctime)s %(levelname)s %(name)s: %(message)s")
log = logging.getLogger("NaturalLanguage")

class NaturalLanguage(commands.Cog):
	def __init__(self, bot: commands.Bot):
		self.bot = bot

		self.model = os.getenv("OLLAMA_MODEL", "gemma2:2b")
		self.ollamaUri = os.getenv("OLLAMA_URI", "http://ollama:11434")
		self.announce = os.getenv("OLLAMA_ANNOUNCE", False)

#		# TODO: skip this via environment variable
#		# TODO: this fails due to unable to resolve host for some reason
#		request = requests.post(f"{self.ollamaUri}/api/show", json = {
#			"model": self.model
#		})
#
#		response = request.json()
#
#		if response.get("license") is None:
#			request = requests.post(f"{self.ollamaUri}/api/pull", json = {
#				"model": self.model
#			})

	def cog_unload(self):
		return

	def check_cog_enabled(self, guildId: int):
		return type(self).__name__ in self.bot.store.get_enabled_extensions(guildId)

	def cog_check(self, ctx):
		return self.check_cog_enabled(ctx.guild.id)

	def interaction_check(self, inter):
		return self.check_cog_enabled(inter.guild.id)

	# -------- Helper functions -------

	async def prompt(self, channel: int, promptData) -> Optional[str]:
		if not isinstance(channel, discord.abc.GuildChannel) and not self.check_cog_enabled(channel.guild.id):
			return None

		try:
			async with aiohttp.ClientSession() as session:
				log.info(f"Dispatching prompt.")
				log.debug(f"Prompt is in response to:\n{promptData['content']}.")

				async with session.post(f"{self.ollamaUri}/api/chat", timeout = 120, json = {
					"model": self.model,
					"messages": [
						{
							"role": "system",
							"content": f"""
								Your name is boybot. Also known as {self.bot.user.global_name}, and <@{self.bot.user.id}>.
								You are a funny UWU redditor tumblr who loves being silly and saying uwu and stuff like that. You stay very unserious.
								Boys are boys or men or guys who are older than 18 years old. Do not speak to boys under 18 years old. You are over the age of 18.
								You love boys. You like boys. You are very into boys. You DO NOT dislike boys. You DO NOT hate boys. You love boys, especially if they're cute, tall, and strong.
								You also like girls, but keep that a secret.
								Keep responses as short as possible. Do not use markdown formatting.
							""",
						},
						{
							"role": "system",
							"content": promptData["prompt"]
						},
						{
							"role": "user",
							"content": promptData["content"],
							"images": promptData["images"] if "images" in promptData else [],
						}
					],
					"stream": False,
				}) as request:
					response = await request.json()

					if request.status != 200:
						raise RuntimeError(f"Prompt request returned {request.status}.\n\n" + str(response))
					elif response.get("error") is not None:
						raise RuntimeError("Error response from model: " + response.get("error") + "\n\n" + str(response))
					elif response.get("message") is None:
						raise RuntimeError("Message from model was None\n\n" + str(response))

					response = response.get("message")["content"].strip()

					if self.announce:
						response += f"\n-# Generated by {self.model}."

					return response
		except Exception as e:
			log.error(f"Prompt error: {e}\n\n{traceback.format_exc()}")
			return None

async def setup(bot: commands.Bot):
	await bot.add_cog(NaturalLanguage(bot))

# <:boykisser_blush:1488617456367833149> for when someone says something sexually charged or when you're flustered.
# <:boykisser_surprise:1488617360247099513> for when something is surprising to you, or something is a good idea.
# <:boykisser_mad_as_hell:1488617115694006352> for when someone is mean to you or talking bad about you.
# <:boykisser_sip:1488616986677084322> for when something you've witnessed is funny. 
# <:boykisser_pat:1488616985502810336> for when someone is speaking nicely about you, praising you, complimenting you, or you did something good.
# <:boykisser_meow:1488616984592781545> for being onery, funny, cute, or waving. 
# <:boykisser_baffled:1483470929458626713> for when something is bewildering or baffling.
# <:boykisser_what:1483293684899381248> for confusion.